FROM node:20-alpine3.18 as build
LABEL authors="Nar Varg"
WORKDIR ../app
COPY package.json .
RUN npm install
COPY . .
ARG REACT_APP_NAME
ENV REACT_APP_NAME=$REACT_APP_NAME
RUN npm run build

FROM nginx:alpine3.18
LABEL authors="Nar Varg"
EXPOSE 80
COPY --from=build /app/nginx/* /usr/share/nginx
COPY --from=build /app/build /usr/share/nginx/html
